name: Snyk Vulnerability Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Snyk
        uses: snyk/actions/setup@v2
        with:
          version: 'latest'

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test Dockerfile
        run: snyk container test --file=Dockerfile

      - name: Test Node.js dependencies
        run: snyk test
